### ISSUE TITLE
Theme broken in Sublime Text 3 Build 3143

### ISSUE THREAD

**Issue by bartdorsey** [bchiang7/Halcyon#1]
Installing the theme from package control and selecting it results in this error. 

<img width="532" alt="screen shot 2018-03-22 at 8 50 34 am" src="https://user-images.githubusercontent.com/362049/37774452-404e3a76-2dae-11e8-96e8-e71c803f91b4.png">

**Comment by bartdorsey** [comment]
Interestingly enough if I fork your repo and clone it into my Packages directory, the theme works, so it's something to do with how a Packed version of this works when package control downloads it.

**Comment by bchiang7** [comment]
Weird, I'll look into it!

**Comment by bchiang7** [comment]
@bartdorsey Figured out what was going on, just submitted a PR for the fix, hopefully it gets merged soon!

**Comment by bchiang7** [comment]
@bartdorsey should be all good now with release 1.0.1. sorry for the delay!
